# 例外処理と名前空間

<div style="text-align: right"><strong>2I06 糸川倫太朗</strong></div>

### 1

> 以下のプログラムを以下の2通りでtry-throw-catchを用いて修正せよ。

#### (ア)

> 例外オブジェクトの型をconst char *とした場合。

```cpp
#include <iostream>
using namespace std;

int main(void) {
  int month, day;
  cout << "今月は何月? ";
  cin >> month;
  cout << "今日は何日? ";
  cin >> day;
  try {
    if (month < 1 || month > 12) {
      throw "月の入力値がおかしい。";
    }
    if (day < 1 || day > 31) {
      throw "日の入力値がおかしい。";
    }
    cout << "今日は" << month << "月" << day << "日です。" << endl;
  }
  catch (const char* err) {
    cout << err << endl;
    return -1;
  }
}

```

#### (イ)

> 例外オブジェクトの型をout_of_rangeとした場合。

```cpp
#include <iostream>
#include <stdexcept>
using namespace std;

int main(void) {
  int month, day;
  cout << "今月は何月? ";
  cin >> month;
  cout << "今日は何日? ";
  cin >> day;
  try {
    if (month < 1 || month > 12 || day < 1 || day > 31) {
      throw out_of_range("out of range");
    }
    cout << "今日は" << month << "月" << day << "日です。" << endl;
  }
  catch (const exception& e) {
    cout << e.what() << endl;
    return -1;
  }
}

```

### 2

> 以下のプログラムを以下の2通りでtry-throw-catchを用いて修正せよ。表示メッセージは、問１と同じとする。

#### (ア)

> 例外オブジェクトの型をconst char *とした場合。 

```cpp
#include <iostream>
#include <string>
using namespace std;

class Date {
  private:
    int month;
    int day;
  public:
    void setMonth(int m) {
      if (m < 1 || m > 12) {
        throw "月の入力値がおかしい。";
      }
      month = m;
    }
    void setDay(int d) {
      if  (d < 1 || d > 31) {
        throw "日の入力値がおかしい。";
      }
      day = d;
    }
    string format(void) {
      return to_string(month) + "月" + to_string(day) + "日";
    }
};

int main(void) {
  Date date;
  int month, day;
  cout << "今月は何月? ";
  cin >> month;
  cout << "今日は何日? ";
  cin >> day;
  try {
    date.setMonth(month);
    date.setDay(day);
    cout << "今日は" << date.format() << "です。" << endl;
  }
  catch (const char* err) {
    cout << err << endl;
    return -1;
  }
  return 0;
}

```

#### (イ)

> 例外オブジェクトの型をout_of_rangeとした場合。

```cpp
#include <iostream>
#include <string>
#include <stdexcept>
using namespace std;

class Date {
  private:
    int month;
    int day;
  public:
    void setMonth(int m) {
      if ( m < 1 || m > 12) {
        throw out_of_range("out of range");
      }
      month = m;
    }
    void setDay(int d) {
      if (d < 1 || d > 31) {
        throw out_of_range("out of range");
      }
      day = d;
    }
    string format(void) {
      return to_string(month) + "月" + to_string(day) + "日";
    }
};

int main(void) {
  Date date;
  int month, day;
  cout << "今月は何月? ";
  cin >> month;
  cout << "今日は何日? ";
  cin >> day;
  try {
    date.setMonth(month);
    date.setDay(day);
    cout << "今日は" << date.format() << "です。" << endl;
  }
  catch (const exception& e) {
    cout << e.what() << endl;
    return -1;
  }
  return 0;
}

```

### 3

> 次のプログラムの表示結果を答えよ。

```bash
re-taro@arch:~/ProgrammingDesign/ExceptionHandlingAndNamespace$ make 3.cpp
あなたは日本語が好きですか?
90
Do you like English?
10
```

